version: '3.8'

services:
  edge-mcp:
    image: ghcr.io/developer-mesh/developer-mesh-edge-mcp:${IMAGE_TAG:-latest}
    container_name: edge-mcp
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 150m
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - PORT=8085  # Edge MCP uses port 8085
      - MCP_CONFIG_FILE=/app/configs/config.production.yaml
    command: /app/edge-mcp
    volumes:
      - ./configs/config.base.yaml:/app/configs/config.base.yaml:ro
      - ./configs/config.production.yaml:/app/configs/config.production.yaml:ro
      - ./configs/config.production.yaml:/app/configs/config.yaml:ro
      - ./configs/auth.production.yaml:/app/configs/auth.production.yaml:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  rest-api:
    image: ghcr.io/developer-mesh/developer-mesh-rest-api:${IMAGE_TAG:-latest}
    container_name: rest-api
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 150m
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - MCP_SERVER_URL=http://edge-mcp:8085
      - PORT=8081  # REST API should use port 8081
      - API_LISTEN_ADDRESS=:8081
      - MIGRATIONS_PATH=/app/migrations/sql  # Set migrations path for REST API
    volumes:
      - ./configs/config.base.yaml:/app/configs/config.base.yaml:ro
      - ./configs/config.production.yaml:/app/configs/config.production.yaml:ro
      - ./configs/config.rest-api.yaml:/app/configs/config.rest-api.yaml:ro
      - ./configs/auth.production.yaml:/app/configs/auth.production.yaml:ro
      - ./logs:/app/logs
    depends_on:
      edge-mcp:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/rest-api", "-health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  worker:
    image: ghcr.io/developer-mesh/developer-mesh-worker:${IMAGE_TAG:-latest}
    container_name: worker
    restart: unless-stopped
    mem_limit: 200m
    mem_reservation: 150m
    env_file:
      - .env
    volumes:
      - ./configs/config.base.yaml:/app/configs/config.base.yaml:ro
      - ./configs/config.production.yaml:/app/configs/config.production.yaml:ro
      - ./configs/auth.production.yaml:/app/configs/auth.production.yaml:ro
      - ./logs:/app/logs
    depends_on:
      edge-mcp:
        condition: service_healthy
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge