# ---- Build Stage ----
FROM golang:1.24-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

# ---- Run Stage ----
FROM alpine:3.18
WORKDIR /app
COPY --from=build /app/worker /app/worker
COPY configs ./configs
RUN apk add --no-cache ca-certificates
ENTRYPOINT ["/app/worker"]
