apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-mcp-config
  namespace: edge-mcp
  labels:
    app: edge-mcp
    app.kubernetes.io/name: edge-mcp
    app.kubernetes.io/component: mcp-server
data:
  # Core Platform connection (optional)
  # Uncomment and set if connecting to Core Platform
  # core-platform-url: "https://core-platform.example.com"

  # Redis cache configuration
  redis-enabled: "true"

  # Tracing configuration (optional)
  # Uncomment to enable distributed tracing
  # tracing-enabled: "true"
  # otlp-endpoint: "jaeger-collector:4317"
