---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-mcp
  namespace: edge-mcp
  labels:
    app: edge-mcp
    app.kubernetes.io/name: edge-mcp
    app.kubernetes.io/component: mcp-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edge-mcp
  namespace: edge-mcp
  labels:
    app: edge-mcp
    app.kubernetes.io/name: edge-mcp
    app.kubernetes.io/component: mcp-server
rules:
# Allow reading ConfigMaps and Secrets (for config hot reload if needed)
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-mcp
  namespace: edge-mcp
  labels:
    app: edge-mcp
    app.kubernetes.io/name: edge-mcp
    app.kubernetes.io/component: mcp-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edge-mcp
subjects:
- kind: ServiceAccount
  name: edge-mcp
  namespace: edge-mcp
