# ServiceMonitor for Prometheus Operator
# Requires Prometheus Operator to be installed in the cluster
# If not using Prometheus Operator, use pod annotations instead (already in deployment.yaml)

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-mcp
  namespace: edge-mcp
  labels:
    app: edge-mcp
    app.kubernetes.io/name: edge-mcp
    app.kubernetes.io/component: mcp-server
    # Add label to match Prometheus's serviceMonitorSelector
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: edge-mcp
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
  namespaceSelector:
    matchNames:
    - edge-mcp
