{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rest-api.secretName" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-api-key: {{ .Values.secrets.adminApiKey.value | required "secrets.adminApiKey.value is required" | quote }}
  reader-api-key: {{ .Values.secrets.readerApiKey.value | required "secrets.readerApiKey.value is required" | quote }}
  mcp-api-key: {{ .Values.secrets.mcpApiKey.value | required "secrets.mcpApiKey.value is required" | quote }}
  {{- if .Values.config.github.enabled }}
  github-token: {{ .Values.secrets.githubToken.value | required "secrets.githubToken.value is required when GitHub is enabled" | quote }}
  github-webhook-secret: {{ .Values.secrets.githubWebhookSecret.value | required "secrets.githubWebhookSecret.value is required when GitHub is enabled" | quote }}
  {{- end }}
  {{- if .Values.config.embedding.openai.enabled }}
  openai-api-key: {{ .Values.secrets.openaiApiKey.value | required "secrets.openaiApiKey.value is required when OpenAI is enabled" | quote }}
  {{- end }}
  {{- if .Values.config.embedding.googleAI.enabled }}
  google-ai-api-key: {{ .Values.secrets.googleAiApiKey.value | required "secrets.googleAiApiKey.value is required when Google AI is enabled" | quote }}
  {{- end }}
{{- end }}
