{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rest-api.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
  annotations:
    {{- include "developer-mesh.serviceAccountAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
