{{- if and .Values.serviceMonitor.enabled .Values.global.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rest-api.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
    {{- if .Values.global.monitoring.prometheusLabel }}
    prometheus: {{ .Values.global.monitoring.prometheusLabel }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rest-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace.name }}
{{- end }}
