openapi: 3.0.0
info:
  title: Collaborations API
  version: 1.0.0
  description: Multi-agent collaboration features

paths:
  /collaborations:
    get:
      tags:
        - Collaboration
      summary: List collaborations
      description: List active multi-agent collaborations
      operationId: listCollaborations
      responses:
        '200':
          description: List of collaborations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collaboration'
    
    post:
      tags:
        - Collaboration
      summary: Create collaboration
      description: Create a new multi-agent collaboration session
      operationId: createCollaboration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollaborationCreate'
      responses:
        '201':
          description: Collaboration created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collaboration'

components:
  schemas:
    Collaboration:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [mapreduce, parallel, consensus]
        agents:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [active, completed, failed]
        created_at:
          type: string
          format: date-time
    
    CollaborationCreate:
      type: object
      required:
        - name
        - type
        - agents
      properties:
        name:
          type: string
        type:
          type: string
          enum: [mapreduce, parallel, consensus]
        agents:
          type: array
          items:
            type: string
          minItems: 2