openapi: 3.0.0
info:
  title: Metrics API
  version: 1.0.0
  description: System metrics and telemetry

paths:
  /metrics:
    get:
      tags:
        - Monitoring
      summary: Get metrics
      description: Retrieve system metrics in Prometheus format
      operationId: getMetrics
      responses:
        '200':
          description: Metrics in Prometheus format
          content:
            text/plain:
              schema:
                type: string
                example: |
                  # HELP http_requests_total Total HTTP requests
                  # TYPE http_requests_total counter
                  http_requests_total{method="GET",path="/api/v1/health"} 1234