openapi: 3.0.0
info:
  title: Monitoring API
  version: 1.0.0
  description: System monitoring and metrics

paths:
  /monitoring/dashboard:
    get:
      tags:
        - Monitoring
      summary: Get monitoring dashboard
      description: Retrieve system monitoring dashboard data
      operationId: getMonitoringDashboard
      responses:
        '200':
          description: Dashboard data
          content:
            application/json:
              schema:
                type: object
                properties:
                  system_status:
                    type: string
                    enum: [healthy, degraded, critical]
                  active_agents:
                    type: integer
                  active_tasks:
                    type: integer
                  success_rate:
                    type: number
                  average_response_time:
                    type: number
                  error_rate:
                    type: number
                  resource_usage:
                    type: object
                    properties:
                      cpu_percent:
                        type: number
                      memory_percent:
                        type: number
                      disk_percent:
                        type: number