openapi: 3.0.0
info:
  title: Relationships API
  version: 1.0.0
  description: Entity relationship management

paths:
  /relationships:
    get:
      tags:
        - Relationships
      summary: List relationships
      description: List all entity relationships
      operationId: listRelationships
      parameters:
        - name: entity_type
          in: query
          schema:
            type: string
        - name: entity_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of relationships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Relationship'
    
    post:
      tags:
        - Relationships
      summary: Create relationship
      description: Create a new entity relationship
      operationId: createRelationship
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipCreate'
      responses:
        '201':
          description: Relationship created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'

  /relationships/{id}:
    get:
      tags:
        - Relationships
      summary: Get relationship
      description: Get a specific relationship by ID
      operationId: getRelationship
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Relationship details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'
        '404':
          description: Relationship not found
    
    delete:
      tags:
        - Relationships
      summary: Delete relationship
      description: Delete a relationship
      operationId: deleteRelationship
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Relationship deleted
        '404':
          description: Relationship not found

  /entities/{type}/{owner}/{repo}/{id}/relationships:
    get:
      tags:
        - Relationships
      summary: Get entity relationships
      description: Get all relationships for a specific entity
      operationId: getEntityRelationships
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Entity relationships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Relationship'

  /entities/{type}/{owner}/{repo}/{id}/graph:
    get:
      tags:
        - Relationships
      summary: Get entity relationship graph
      description: Get the full relationship graph for an entity
      operationId: getEntityGraph
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: depth
          in: query
          schema:
            type: integer
            default: 2
      responses:
        '200':
          description: Relationship graph
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                  edges:
                    type: array
                    items:
                      type: object

components:
  schemas:
    Relationship:
      type: object
      properties:
        id:
          type: string
        source_type:
          type: string
        source_id:
          type: string
        target_type:
          type: string
        target_id:
          type: string
        relationship_type:
          type: string
        created_at:
          type: string
          format: date-time
    
    RelationshipCreate:
      type: object
      required:
        - source_type
        - source_id
        - target_type
        - target_id
        - relationship_type
      properties:
        source_type:
          type: string
        source_id:
          type: string
        target_type:
          type: string
        target_id:
          type: string
        relationship_type:
          type: string