openapi: 3.0.0
info:
  title: Vector API
  version: 1.0.0
  description: Vector storage and similarity search operations

paths:
  /vectors:
    post:
      tags:
        - Vectors
      summary: Store vector embedding
      description: Store a vector embedding with associated metadata
      operationId: storeVector
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - embedding
                - metadata
              properties:
                embedding:
                  type: array
                  items:
                    type: number
                  description: Vector embedding
                metadata:
                  type: object
                  description: Associated metadata
      responses:
        '201':
          description: Vector stored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Vector ID
                  message:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /vectors/search:
    post:
      tags:
        - Vectors
      summary: Search similar vectors
      description: Find vectors similar to the query vector
      operationId: searchVectors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query_vector
              properties:
                query_vector:
                  type: array
                  items:
                    type: number
                  description: Query vector
                limit:
                  type: integer
                  default: 10
                  description: Maximum number of results
                threshold:
                  type: number
                  default: 0.7
                  description: Similarity threshold
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        similarity:
                          type: number
                        metadata:
                          type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error