openapi: 3.0.0
info:
  title: Workflows API
  version: 1.0.0
  description: Multi-step workflow orchestration

paths:
  /workflows:
    get:
      tags:
        - Workflows
      summary: List workflows
      description: List all defined workflows
      operationId: listWorkflows
      responses:
        '200':
          description: List of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workflow'
    
    post:
      tags:
        - Workflows
      summary: Create workflow
      description: Create a new workflow definition
      operationId: createWorkflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowCreate'
      responses:
        '201':
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'

  /workflows/{id}:
    get:
      tags:
        - Workflows
      summary: Get workflow
      description: Get workflow definition by ID
      operationId: getWorkflow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workflow details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '404':
          description: Workflow not found
    
    put:
      tags:
        - Workflows
      summary: Update workflow
      description: Update workflow definition
      operationId: updateWorkflow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowUpdate'
      responses:
        '200':
          description: Workflow updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
    
    delete:
      tags:
        - Workflows
      summary: Delete workflow
      description: Delete workflow definition
      operationId: deleteWorkflow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Workflow deleted
        '404':
          description: Workflow not found

  /workflows/{id}/executions:
    get:
      tags:
        - Workflows
      summary: List workflow executions
      description: List executions of a workflow
      operationId: listWorkflowExecutions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of executions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkflowExecution'
    
    post:
      tags:
        - Workflows
      summary: Execute workflow
      description: Start a new workflow execution
      operationId: executeWorkflow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  description: Workflow input parameters
      responses:
        '201':
          description: Execution started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowExecution'

components:
  schemas:
    Workflow:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowStep'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
    WorkflowCreate:
      type: object
      required:
        - name
        - steps
      properties:
        name:
          type: string
        description:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowStep'
    
    WorkflowUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowStep'
    
    WorkflowStep:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        config:
          type: object
    
    WorkflowExecution:
      type: object
      properties:
        id:
          type: string
        workflow_id:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed]
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        input:
          type: object
        output:
          type: object
        error:
          type: string