run:
  timeout: 10m
  modules-download-mode: readonly
  go: '1.24.4'
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - mocks
    - .git
    - build
    - dist
    - node_modules

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - unconvert
    - dupl
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - goconst
    - gocyclo
    - gocognit
    - whitespace
    - unparam
    - revive

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/devops-mcp
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocognit:
    min-complexity: 20
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    check-exported: false
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - path: test/
      linters:
        - gosec
        - dupl
    - path: cmd/
      linters:
        - gocyclo
        - gocognit
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "don't use an underscore in package name"
      linters:
        - revive
    - path: ".*\\.pb\\.go"
      linters:
        - gocyclo
        - gocognit
        - gocritic
        - govet
        - ineffassign
        - staticcheck
        - unused

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true