{{- if .Values.global.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.name }}
  labels:
    {{- include "developer-mesh.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace.name }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
