{{- if not .Values.global.database.existingSecret }}
{{- if not .Values.global.database.embedded }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developer-mesh.fullname" . }}-database-secret
  namespace: {{ include "developer-mesh.namespace" . }}
  labels:
    {{- include "developer-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.global.database.password | required "global.database.password is required when not using embedded database or existingSecret" | quote }}
{{- end }}
{{- end }}

{{- if not .Values.global.redis.existingSecret }}
{{- if not .Values.global.redis.embedded }}
{{- if .Values.global.redis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developer-mesh.fullname" . }}-redis-secret
  namespace: {{ include "developer-mesh.namespace" . }}
  labels:
    {{- include "developer-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.global.redis.password | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- if not .Values.global.aws.existingSecret }}
{{- if and .Values.global.aws.accessKeyId .Values.global.aws.secretAccessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developer-mesh.fullname" . }}-aws-secret
  namespace: {{ include "developer-mesh.namespace" . }}
  labels:
    {{- include "developer-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.global.aws.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.global.aws.secretAccessKey | quote }}
{{- end }}
{{- end }}

{{- if not .Values.global.security.jwt.existingSecret }}
{{- if .Values.global.security.jwt.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developer-mesh.fullname" . }}-jwt-secret
  namespace: {{ include "developer-mesh.namespace" . }}
  labels:
    {{- include "developer-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.security.jwt.secret | quote }}
{{- end }}
{{- end }}

{{- if not .Values.global.security.existingSecret }}
{{- if .Values.global.security.encryptionMasterKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developer-mesh.fullname" . }}-encryption-secret
  namespace: {{ include "developer-mesh.namespace" . }}
  labels:
    {{- include "developer-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption-master-key: {{ .Values.global.security.encryptionMasterKey | quote }}
{{- end }}
{{- end }}
