apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-mcp.fullname" . }}-secrets
  namespace: {{ include "edge-mcp.namespace" . }}
  labels:
    {{- include "edge-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.edgeMcp.auth.apiKey | quote }}
  {{- if .Values.edgeMcp.corePlatform.enabled }}
  core-platform-api-key: {{ .Values.edgeMcp.corePlatform.apiKey | quote }}
  {{- end }}
