#!/bin/bash

# Apply nginx WebSocket fix via AWS SSM

INSTANCE_ID="i-08a9a59532aad9879"

echo "Applying nginx WebSocket configuration via SSM..."

# Create the nginx configuration
aws ssm send-command \
  --instance-ids "$INSTANCE_ID" \
  --document-name "AWS-RunShellScript" \
  --parameters 'commands=[
    "sudo tee /etc/nginx/conf.d/mcp.conf > /dev/null << '\''EOF'\''",
    "# MCP Server Configuration",
    "server {",
    "    listen 80;",
    "    server_name mcp.dev-mesh.io;",
    "    return 301 https://\$server_name\$request_uri;",
    "}",
    "",
    "server {",
    "    listen 443 ssl;",
    "    server_name mcp.dev-mesh.io;",
    "    ",
    "    ssl_certificate /etc/letsencrypt/live/mcp.dev-mesh.io/fullchain.pem;",
    "    ssl_certificate_key /etc/letsencrypt/live/mcp.dev-mesh.io/privkey.pem;",
    "    ",
    "    add_header X-Frame-Options \"SAMEORIGIN\" always;",
    "    add_header X-Content-Type-Options \"nosniff\" always;",
    "    add_header X-XSS-Protection \"1; mode=block\" always;",
    "    ",
    "    # WebSocket endpoint",
    "    location /ws {",
    "        proxy_pass http://localhost:8080;",
    "        proxy_http_version 1.1;",
    "        proxy_set_header Upgrade \$http_upgrade;",
    "        proxy_set_header Connection \"upgrade\";",
    "        proxy_set_header Host \$host;",
    "        proxy_set_header X-Real-IP \$remote_addr;",
    "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto \$scheme;",
    "        proxy_connect_timeout 7d;",
    "        proxy_send_timeout 7d;",
    "        proxy_read_timeout 7d;",
    "        proxy_buffering off;",
    "    }",
    "    ",
    "    location / {",
    "        proxy_pass http://localhost:8080;",
    "        proxy_set_header Host \$host;",
    "        proxy_set_header X-Real-IP \$remote_addr;",
    "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto \$scheme;",
    "        proxy_connect_timeout 60s;",
    "        proxy_send_timeout 60s;",
    "        proxy_read_timeout 60s;",
    "    }",
    "}",
    "",
    "server {",
    "    listen 80;",
    "    server_name api.dev-mesh.io;",
    "    return 301 https://\$server_name\$request_uri;",
    "}",
    "",
    "server {",
    "    listen 443 ssl;",
    "    server_name api.dev-mesh.io;",
    "    ",
    "    ssl_certificate /etc/letsencrypt/live/api.dev-mesh.io/fullchain.pem;",
    "    ssl_certificate_key /etc/letsencrypt/live/api.dev-mesh.io/privkey.pem;",
    "    ",
    "    add_header X-Frame-Options \"SAMEORIGIN\" always;",
    "    add_header X-Content-Type-Options \"nosniff\" always;",
    "    add_header X-XSS-Protection \"1; mode=block\" always;",
    "    ",
    "    location / {",
    "        proxy_pass http://localhost:8081;",
    "        proxy_set_header Host \$host;",
    "        proxy_set_header X-Real-IP \$remote_addr;",
    "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto \$scheme;",
    "        proxy_connect_timeout 60s;",
    "        proxy_send_timeout 60s;",
    "        proxy_read_timeout 60s;",
    "    }",
    "}",
    "EOF"
  ]' \
  --output json | jq -r '.Command.CommandId'