openapi: 3.0.0
info:
  title: Webhooks API
  version: 1.0.0
  description: Webhook management and event processing

paths:
  /webhooks/github:
    post:
      tags:
        - Webhooks
      summary: Handle GitHub webhook
      description: Process incoming GitHub webhook events
      operationId: handleGitHubWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: GitHub webhook payload
      responses:
        '200':
          description: Webhook processed successfully
        '400':
          description: Invalid webhook payload
        '401':
          description: Invalid webhook signature
        '500':
          description: Internal server error

  /webhooks/github/config:
    get:
      tags:
        - Webhooks
      summary: Get GitHub webhook configuration
      description: Retrieve current GitHub webhook configuration
      operationId: getGitHubWebhookConfig
      responses:
        '200':
          description: Configuration retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook_url:
                    type: string
                  events:
                    type: array
                    items:
                      type: string
                  active:
                    type: boolean
    
    put:
      tags:
        - Webhooks
      summary: Update GitHub webhook configuration
      description: Update GitHub webhook configuration
      operationId: updateGitHubWebhookConfig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                events:
                  type: array
                  items:
                    type: string
                active:
                  type: boolean
      responses:
        '200':
          description: Configuration updated

  /webhooks/events:
    get:
      tags:
        - Webhooks
      summary: List webhook events
      description: Retrieve list of received webhook events
      operationId: listWebhookEvents
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of webhook events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        received_at:
                          type: string
                          format: date-time
                        status:
                          type: string
                  total:
                    type: integer

  /webhooks/events/{id}:
    get:
      tags:
        - Webhooks
      summary: Get webhook event
      description: Retrieve details of a specific webhook event
      operationId: getWebhookEvent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Webhook event details
        '404':
          description: Event not found

  /webhooks/events/{id}/retry:
    post:
      tags:
        - Webhooks
      summary: Retry webhook event
      description: Retry processing of a failed webhook event
      operationId: retryWebhookEvent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retry initiated
        '404':
          description: Event not found

  /webhooks/secrets/rotate:
    post:
      tags:
        - Webhooks
      summary: Rotate webhook secret
      description: Rotate the webhook signing secret
      operationId: rotateWebhookSecret
      responses:
        '200':
          description: Secret rotated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_secret:
                    type: string
                  expires_at:
                    type: string
                    format: date-time