apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  # Worker configuration
  worker.yaml: |
    concurrency: {{ .Values.config.concurrency }}
    queueType: {{ .Values.config.queueType }}
    embedding:
      defaultModel: {{ .Values.config.embedding.defaultModel }}
      chunkSize: {{ .Values.config.embedding.chunkSize }}
      batchSize: {{ .Values.config.embedding.batchSize }}
