# Default values for worker subchart
# These can be overridden by parent chart

nameOverride: ""
fullnameOverride: ""

# Replica count (overridden by HPA when enabled)
replicaCount: 2

# Image configuration
image:
  repository: developer-mesh/worker
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

imagePullSecrets: []

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# RBAC
rbac:
  create: true

# Application configuration
config:
  # Core settings
  environment: "production"
  logLevel: "info"
  logFormat: "json"

  # Worker settings
  concurrency: 5
  queueType: "redis"

  # Embedding processing
  embedding:
    defaultModel: "amazon.titan-embed-text-v2:0"
    chunkSize: 1000
    batchSize: 10

  # Bedrock configuration
  bedrock:
    enabled: true

# Resource limits
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Security context
# Worker uses standard non-root user (UID 65532)
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  readOnlyRootFilesystem: true

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels:
  app: worker

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity rules
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - worker
          topologyKey: kubernetes.io/hostname

# Init containers
initContainers:
  # Wait for database
  waitForDatabase:
    enabled: true
    image: busybox:1.36
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

  # Wait for Redis
  waitForRedis:
    enabled: true
    image: busybox:1.36
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
