# RAG Loader Configuration - Multi-Tenant API Mode
# Sources are now managed dynamically via REST API, not config file

service:
  port: 8084
  metrics_port: 9094
  health_check_interval: 30s
  shutdown_timeout: 30s
  log_level: debug

database:
  host: ${DATABASE_HOST}
  port: 5432
  database: ${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  ssl_mode: ${DATABASE_SSL_MODE}
  search_path: rag,mcp,public
  max_conns: 10
  max_idle_conns: 5

redis:
  address: ${REDIS_ADDR}
  password: ""
  database: 0
  max_retries: 3
  dial_timeout: 5s
  pool_size: 10

# Data sources - EMPTY for multi-tenant API mode
# Configure sources via REST API: POST /api/v1/rag/sources
sources: []

processing:
  chunking_strategy: fixed
  chunk_size: 500
  chunk_overlap: 50

  embedding:
    batch_size: 10
    rate_limit_rpm: 100
    retry_attempts: 3
    retry_delay: 1s
    model_override: ""

  circuit_breaker:
    failure_threshold: 5
    success_threshold: 2
    timeout: 30s
    half_open_max_requests: 3

search:
  vector_weight: 0.6
  bm25_weight: 0.2
  importance_weight: 0.2
  mmr_lambda: 0.7
  min_score: 0.4
  default_limit: 20
  max_candidates: 100
  apply_mmr: true

rate_limiting:
  enabled: true
  embedding_rpm: 100
  search_rpm: 200
  api_rpm: 50
  burst_multiplier: 2

scheduler:
  default_schedule: "*/30 * * * *"
  job_timeout: 10m
  enable_api: true
  enable_events: false  # Events disabled for Phase 1
  max_concurrent_jobs: 3
